// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {logring} from '../models';
import {io} from '../models';
import {frontend} from '../models';

export function Deploy(arg1:string):Promise<string>;

export function ExportBundle(arg1:app.ExportRequest):Promise<app.ExportResult>;

export function GetConfig():Promise<app.ConfigView>;

export function GetLogs(arg1:number):Promise<Array<logring.Entry>>;

export function GetOverview():Promise<app.Overview>;

export function ImportBundle(arg1:app.ImportRequest):Promise<string>;

export function ListCertificates():Promise<Array<app.CertView>>;

export function LogWriter():Promise<io.Writer>;

export function PreviewImportBundle(arg1:app.ImportPreviewRequest):Promise<app.ImportPreview>;

export function RebuildAndRestart():Promise<string>;

export function ReloadConfig():Promise<string>;

export function Renew(arg1:string):Promise<string>;

export function RunCheck():Promise<string>;

export function RunOnce():Promise<string>;

export function SaveConfig(arg1:app.ConfigView):Promise<string>;

export function SelectOpenPath(arg1:frontend.OpenDialogOptions):Promise<string>;

export function SelectSavePath(arg1:frontend.SaveDialogOptions):Promise<string>;

export function TestNotify():Promise<string>;

export function TestSSH(arg1:app.SSHTestParams):Promise<string>;
