// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Deploy(arg1) {
  return window['go']['app']['App']['Deploy'](arg1);
}

export function ExportBundle(arg1) {
  return window['go']['app']['App']['ExportBundle'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetOverview() {
  return window['go']['app']['App']['GetOverview']();
}

export function ImportBundle(arg1) {
  return window['go']['app']['App']['ImportBundle'](arg1);
}

export function ListCertificates() {
  return window['go']['app']['App']['ListCertificates']();
}

export function LogWriter() {
  return window['go']['app']['App']['LogWriter']();
}

export function PreviewImportBundle(arg1) {
  return window['go']['app']['App']['PreviewImportBundle'](arg1);
}

export function RebuildAndRestart() {
  return window['go']['app']['App']['RebuildAndRestart']();
}

export function ReloadConfig() {
  return window['go']['app']['App']['ReloadConfig']();
}

export function Renew(arg1) {
  return window['go']['app']['App']['Renew'](arg1);
}

export function RunCheck() {
  return window['go']['app']['App']['RunCheck']();
}

export function RunOnce() {
  return window['go']['app']['App']['RunOnce']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SelectOpenPath(arg1) {
  return window['go']['app']['App']['SelectOpenPath'](arg1);
}

export function SelectSavePath(arg1) {
  return window['go']['app']['App']['SelectSavePath'](arg1);
}

export function TestNotify() {
  return window['go']['app']['App']['TestNotify']();
}

export function TestSSH(arg1) {
  return window['go']['app']['App']['TestSSH'](arg1);
}
